### ISSUE TITLE
Checkin of CPLEX instances missing

### ISSUE THREAD

**Issue by beyeler** [blubin/JOpt#26]
In the method

https://github.com/blubin/JOpt/blob/ebe63dea765f4e344abd45b09359bcac3c654d6e/src/main/java/edu/harvard/econcs/jopt/solver/server/cplex/CPlexMIPSolver.java#L584

a CPLEX instance is checked out but never checked in again. When the max number of CPLEX instances is reached the program waits for an instances returned to the CPLEXInstanceManager which will never happen.

**Comment by blubin** [comment]
Yes, looks like a bug.  The instance should be released at the end of the call in a "finally" block...   A PR would be welcomed.

**Comment by islerfab** [comment]
I pushed a fix, thanks @beyeler for pointing it out. The easiest is always a PR on the "develop" branch, but that way it was quick as way.

Release v1.4.2 is initiated, and will be online in the next few minutes/hours.
